### ISSUE TITLE
Load distro specific vars

### ISSUE THREAD

**Issue by frankenfr** [csmart/virt-infra-ansible#4]
I'm getting the following issue:
TASK [ansible-role-virt-infra : KVM host only: Load distro specific vars] **********************************************
fatal: [localhost]: FAILED! => {"ansible_facts": {}, "ansible_included_var_files": [], "changed": false, "message": "Could not find or access 'pop!_os.yml'

**Comment by csmart** [comment]
Hi @frankenfr, there is no `yaml` file for support for `pop!_os` and so it can't load the defaults. However I think it's based on Ubuntu, so you should be able to just link the `ubuntu.yml` file to `pop!_os.yml` whether you have the role, and try again.

If you can browse to where the role is, then go into the vars dir and link it.

```bash
cd vars/
ln -s ubuntu.yml pop\!_os.yml
```

Then you can try again and see if it works.

I'll see if I can work out how to add support for it properly. To help with that, could you please paste the contents of `/etc/os-release`?

Thanks,
-c

**Comment by csmart** [comment]
Closing as I couldn't get the value of `/etc/os-release` in order to make it supported.
